# Generated by Django 5.1.4 on 2025-12-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pode_reservar',
            field=models.BooleanField(default=False, verbose_name='Pode fazer reservas'),
        ),
    ]
